[2025-02-14 02:12:04,069] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: Project.task_zero 2025-02-14T02:12:03.529015+00:00 [queued]>
[2025-02-14 02:12:04,091] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: Project.task_zero 2025-02-14T02:12:03.529015+00:00 [queued]>
[2025-02-14 02:12:04,092] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2025-02-14 02:12:04,092] {taskinstance.py:1088} INFO - Starting attempt 1 of 3
[2025-02-14 02:12:04,093] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2025-02-14 02:12:04,106] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_zero> on 2025-02-14T02:12:03.529015+00:00
[2025-02-14 02:12:04,115] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Project', 'task_zero', '2025-02-14T02:12:03.529015+00:00', '--job-id', '106', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/assignment.py', '--cfg-path', '/tmp/tmpvr878yo0', '--error-file', '/tmp/tmp0dmgks4f']
[2025-02-14 02:12:04,109] {standard_task_runner.py:52} INFO - Started process 4021 to run task
[2025-02-14 02:12:04,116] {standard_task_runner.py:77} INFO - Job 106: Subtask task_zero
[2025-02-14 02:12:04,164] {logging_mixin.py:104} INFO - Running <TaskInstance: Project.task_zero 2025-02-14T02:12:03.529015+00:00 [running]> on host 81ce9e7c2327
[2025-02-14 02:12:04,217] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Project
AIRFLOW_CTX_TASK_ID=task_zero
AIRFLOW_CTX_EXECUTION_DATE=2025-02-14T02:12:03.529015+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-02-14T02:12:03.529015+00:00
[2025-02-14 02:12:04,218] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2025-02-14 02:12:04,220] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'pip install beautifulsoup4']
[2025-02-14 02:12:04,228] {subprocess.py:75} INFO - Output:
[2025-02-14 02:12:05,297] {subprocess.py:79} INFO - Defaulting to user installation because normal site-packages is not writeable
[2025-02-14 02:12:05,367] {subprocess.py:79} INFO - Requirement already satisfied: beautifulsoup4 in /home/***/.local/lib/python3.6/site-packages (4.12.3)
[2025-02-14 02:12:05,373] {subprocess.py:79} INFO - Requirement already satisfied: soupsieve>1.2 in /home/***/.local/lib/python3.6/site-packages (from beautifulsoup4) (2.3.2.post1)
[2025-02-14 02:12:10,255] {subprocess.py:83} INFO - Command exited with return code 0
[2025-02-14 02:12:10,290] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=Project, task_id=task_zero, execution_date=20250214T021203, start_date=20250214T021204, end_date=20250214T021210
[2025-02-14 02:12:10,320] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-14 02:12:10,338] {local_task_job.py:151} INFO - Task exited with return code 0
