[2025-02-14 03:11:17,497] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: Project.task_zero 2025-02-14T03:11:16.276498+00:00 [queued]>
[2025-02-14 03:11:17,510] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: Project.task_zero 2025-02-14T03:11:16.276498+00:00 [queued]>
[2025-02-14 03:11:17,510] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2025-02-14 03:11:17,511] {taskinstance.py:1088} INFO - Starting attempt 1 of 3
[2025-02-14 03:11:17,511] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2025-02-14 03:11:17,525] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_zero> on 2025-02-14T03:11:16.276498+00:00
[2025-02-14 03:11:17,529] {standard_task_runner.py:52} INFO - Started process 1185 to run task
[2025-02-14 03:11:17,534] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Project', 'task_zero', '2025-02-14T03:11:16.276498+00:00', '--job-id', '128', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/assignment.py', '--cfg-path', '/tmp/tmpqhgc4nwf', '--error-file', '/tmp/tmps35dyzwe']
[2025-02-14 03:11:17,535] {standard_task_runner.py:77} INFO - Job 128: Subtask task_zero
[2025-02-14 03:11:17,584] {logging_mixin.py:104} INFO - Running <TaskInstance: Project.task_zero 2025-02-14T03:11:16.276498+00:00 [running]> on host 9e3f73609008
[2025-02-14 03:11:17,654] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Project
AIRFLOW_CTX_TASK_ID=task_zero
AIRFLOW_CTX_EXECUTION_DATE=2025-02-14T03:11:16.276498+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-02-14T03:11:16.276498+00:00
[2025-02-14 03:11:17,655] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2025-02-14 03:11:17,657] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'pip install beautifulsoup4']
[2025-02-14 03:11:17,677] {subprocess.py:75} INFO - Output:
[2025-02-14 03:11:19,464] {subprocess.py:79} INFO - Defaulting to user installation because normal site-packages is not writeable
[2025-02-14 03:11:19,557] {subprocess.py:79} INFO - Requirement already satisfied: beautifulsoup4 in /home/***/.local/lib/python3.6/site-packages (4.12.3)
[2025-02-14 03:11:19,565] {subprocess.py:79} INFO - Requirement already satisfied: soupsieve>1.2 in /home/***/.local/lib/python3.6/site-packages (from beautifulsoup4) (2.3.2.post1)
[2025-02-14 03:11:24,217] {subprocess.py:83} INFO - Command exited with return code 0
[2025-02-14 03:11:24,248] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=Project, task_id=task_zero, execution_date=20250214T031116, start_date=20250214T031117, end_date=20250214T031124
[2025-02-14 03:11:24,284] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-14 03:11:24,329] {local_task_job.py:151} INFO - Task exited with return code 0
