[2025-02-14 02:29:39,924] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: Project.task_zero 2025-02-14T02:29:39.228867+00:00 [queued]>
[2025-02-14 02:29:39,944] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: Project.task_zero 2025-02-14T02:29:39.228867+00:00 [queued]>
[2025-02-14 02:29:39,944] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2025-02-14 02:29:39,945] {taskinstance.py:1088} INFO - Starting attempt 1 of 3
[2025-02-14 02:29:39,945] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2025-02-14 02:29:39,955] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_zero> on 2025-02-14T02:29:39.228867+00:00
[2025-02-14 02:29:39,959] {standard_task_runner.py:52} INFO - Started process 1142 to run task
[2025-02-14 02:29:39,964] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Project', 'task_zero', '2025-02-14T02:29:39.228867+00:00', '--job-id', '116', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/assignment.py', '--cfg-path', '/tmp/tmp6o5l33hq', '--error-file', '/tmp/tmpx70c4fdp']
[2025-02-14 02:29:39,965] {standard_task_runner.py:77} INFO - Job 116: Subtask task_zero
[2025-02-14 02:29:40,032] {logging_mixin.py:104} INFO - Running <TaskInstance: Project.task_zero 2025-02-14T02:29:39.228867+00:00 [running]> on host ad36e95eb2b4
[2025-02-14 02:29:40,092] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Project
AIRFLOW_CTX_TASK_ID=task_zero
AIRFLOW_CTX_EXECUTION_DATE=2025-02-14T02:29:39.228867+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-02-14T02:29:39.228867+00:00
[2025-02-14 02:29:40,093] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2025-02-14 02:29:40,094] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'pip install beautifulsoup4']
[2025-02-14 02:29:40,103] {subprocess.py:75} INFO - Output:
[2025-02-14 02:29:41,053] {subprocess.py:79} INFO - Defaulting to user installation because normal site-packages is not writeable
[2025-02-14 02:29:41,148] {subprocess.py:79} INFO - Requirement already satisfied: beautifulsoup4 in /home/***/.local/lib/python3.6/site-packages (4.12.3)
[2025-02-14 02:29:41,157] {subprocess.py:79} INFO - Requirement already satisfied: soupsieve>1.2 in /home/***/.local/lib/python3.6/site-packages (from beautifulsoup4) (2.3.2.post1)
[2025-02-14 02:29:45,922] {subprocess.py:83} INFO - Command exited with return code 0
[2025-02-14 02:29:45,957] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=Project, task_id=task_zero, execution_date=20250214T022939, start_date=20250214T022939, end_date=20250214T022945
[2025-02-14 02:29:45,993] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-14 02:29:46,016] {local_task_job.py:151} INFO - Task exited with return code 0
