[2025-02-14 02:09:23,671] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: Project.task_zero 2025-02-14T02:09:23.000068+00:00 [queued]>
[2025-02-14 02:09:23,688] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: Project.task_zero 2025-02-14T02:09:23.000068+00:00 [queued]>
[2025-02-14 02:09:23,688] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2025-02-14 02:09:23,689] {taskinstance.py:1088} INFO - Starting attempt 1 of 3
[2025-02-14 02:09:23,689] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2025-02-14 02:09:23,697] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_zero> on 2025-02-14T02:09:23.000068+00:00
[2025-02-14 02:09:23,705] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Project', 'task_zero', '2025-02-14T02:09:23.000068+00:00', '--job-id', '104', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/assignment.py', '--cfg-path', '/tmp/tmp20jd77ga', '--error-file', '/tmp/tmpfgspqk7m']
[2025-02-14 02:09:23,706] {standard_task_runner.py:77} INFO - Job 104: Subtask task_zero
[2025-02-14 02:09:23,700] {standard_task_runner.py:52} INFO - Started process 3759 to run task
[2025-02-14 02:09:23,752] {logging_mixin.py:104} INFO - Running <TaskInstance: Project.task_zero 2025-02-14T02:09:23.000068+00:00 [running]> on host 81ce9e7c2327
[2025-02-14 02:09:23,813] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Project
AIRFLOW_CTX_TASK_ID=task_zero
AIRFLOW_CTX_EXECUTION_DATE=2025-02-14T02:09:23.000068+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-02-14T02:09:23.000068+00:00
[2025-02-14 02:09:23,814] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2025-02-14 02:09:23,815] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'pip install beautifulsoup4']
[2025-02-14 02:09:23,824] {subprocess.py:75} INFO - Output:
[2025-02-14 02:09:24,907] {subprocess.py:79} INFO - Defaulting to user installation because normal site-packages is not writeable
[2025-02-14 02:09:25,033] {subprocess.py:79} INFO - Requirement already satisfied: beautifulsoup4 in /home/***/.local/lib/python3.6/site-packages (4.12.3)
[2025-02-14 02:09:25,043] {subprocess.py:79} INFO - Requirement already satisfied: soupsieve>1.2 in /home/***/.local/lib/python3.6/site-packages (from beautifulsoup4) (2.3.2.post1)
[2025-02-14 02:09:29,910] {subprocess.py:83} INFO - Command exited with return code 0
[2025-02-14 02:09:29,943] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=Project, task_id=task_zero, execution_date=20250214T020923, start_date=20250214T020923, end_date=20250214T020929
[2025-02-14 02:09:29,974] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-14 02:09:30,002] {local_task_job.py:151} INFO - Task exited with return code 0
